### ISSUE TITLE
When player wins, they keep the things in their inventory

### ISSUE THREAD

**Issue by DanielRamosAcosta** [walrusone/SkyWarsReloaded#13]
I don't really know if it's a plugin conflict or something, but in the console I'm not having any error.

When a player wins a map, if they rejoin that same map, they are having the same items that they had the last match.

Here is a list of my plugins:
- iConomy
- PermissionsEx
- TuxTwoLib
- MultiWorld
- WorldEdit
- MultiInv
- Vault
- SkyWarsReloaded
- ProtocolLib
- AuthMe
- AutoIn

**Comment by walrusone** [comment]
This is a multiInv issue. I'll look into it before my next release. Thanks.

**Comment by DanielRamosAcosta** [comment]
Thanks a lot! BTW, is there any alternative to MultiInv that may solve this issue?

**Comment by walrusone** [comment]
Not that I know of.

**Comment by walrusone** [comment]
I think I have this fixed. Should work correctly in next release.

**Comment by DanielRamosAcosta** [comment]
Thanks a lot again! :+1:
