### ISSUE TITLE
Cannot Set Price on Kit

### ISSUE THREAD

**Issue by gavinmmccabe** [walrusone/SkyWarsReloaded#27]
There are no errors to show on this, but I set a permcost in the kits configuration but it doesn't put a price in game, it just says free.  This issue could make me stop using the plugin.  Also the rank that I'm testing on does not have the awe.kit.free.kit permission.

**Comment by badbones69** [comment]
Hi I was having the same problem but I found out I gave players the perm swr.kit.\* and it would give them access to the kits but it would also give them the kits for free. So go back and remove that perm if you have it and then just give them each kit perm individually.

**Comment by CoolLord22** [comment]
I found out why! When you give the permission node swr.kit.* it also includes swr.kit.free! That gives them the kits for free! All you have to do is give them swr.kit.<KITNAME>
