### ISSUE TITLE
Plugin Area Detection Problem (Ussing last version)

### ISSUE THREAD

**Issue by quiquelhappy** [walrusone/SkyWarsReloaded#28]
I have a big problem. SkyWarsReloaded is on the LAST version and does not load properly my arena, the arena is: [I SEND YOU THE ARENA BY PM ON SPIGOTMC] and the problem it that: the plugin does not detect the beacon and don't create the spawnpoint, and, the chest are not refilled. It is like the plugin does not record the fullmap and don't detect the islands to the full area...

**Comment by quiquelhappy** [comment]
![2015-08-11_12 32 20](https://cloud.githubusercontent.com/assets/12534357/9196592/46691bcc-402d-11e5-861a-faaf6459adf2.png)
In this sceenshot you can see that there are 3 islands that works, but not the others, in the islands that the spawns worked, the chest works too, in all the others does not work the chest and the spawns as I said

**Comment by walrusone** [comment]
Read the plugin description. Your map must be larger than the scanning area. You can increase the max map size in the config, but you should also make sure the map is centered around 0,0.
