### ISSUE TITLE
Spectators can fall players

### ISSUE THREAD

**Issue by Alexre** [walrusone/SkyWarsReloaded#32]
The spectators can stay in front of a player that is making a bridge and the player falls.

There is a tp system with the plugin, but sometimes fails

**Comment by Elgorond** [comment]
I've also seen it fail. Maybe an idea is to not allow spectators go within 5 blocks of a player?

**Comment by SpoopyDev** [comment]
Well I figure out someway to fix this, maybe ill just use the real spectator mode. It should disallow the spectator from interfering with players.

**Comment by Malachiel87** [comment]
a related thing, spectator can open chest and duplicate items out, then have these item at lobby...

**Comment by RobiRami** [comment]
Xion87, could you create an issue on Github about the spectator issues that you have ?

**Comment by Malachiel87** [comment]
sure ^^

**Comment by Alexre** [comment]
Robi can you revise the spectators, they can fall players

**Comment by RobiRami** [comment]
I will take a look at it
