### ISSUE TITLE
[Suggestion] Round timeout?

### ISSUE THREAD

**Issue by L4BORG** [walrusone/SkyWarsReloaded#33]
Maximum round time limit for each round would be nice, something like 15 or 20 minutes, maybe with countdown (last 3 minutes).

**Comment by HandGrenade** [comment]
You are able to set a maximum time limit for games in the config.yml. It's on like 43, '  maxGameLength: 15' Put in any number, and it will set the limit to be that amount in minutes. For the message, you can customize it in the messages.yml. Lines 32 & 33:
gameEndingTimer: &6 Game Ending in &4{time}&6 Minutes!'
forceGameEnd: '&4 Game Ending. Time Limit Reached!'

**Comment by L4BORG** [comment]
Thx, my bad :$
