### ISSUE TITLE
permissions break and place only for skywar game

### ISSUE THREAD

**Issue by Simonchan93729** [walrusone/SkyWarsReloaded#45]
I've limited Members When they go into skywar game they can't break anything
What can I do? 

my lobby has ban break and place 
if unban  break and place will can  break and place in lobby
but ban  break and place can't  break and place in skywar
please help me thankyou

**Comment by Struck713** [comment]
Go into the server.properties file and change
`spawn-protection=16`
to 
`spawn-protection=0`
