### ISSUE TITLE
Nice Job!!

### ISSUE THREAD

**Issue by ElPresidentePro** [walrusone/SkyWarsReloaded#5]
It´s amazing ty my friend ;) but what is your program for compiling Postdata: i use netbeans.

**Comment by walrusone** [comment]
I'm using eclipse.  Also I find if I update using maven I have to reset the project compatibility for 1.7. I have to look into that to see what's happening. 

I haven't used netbeans, but when you import the root directory in eclipse it automatically recognises all the folders.

**Comment by ElPresidentePro** [comment]
ok, thanks my friend ;)
