### ISSUE TITLE
Skywars --> SkywarsReloaded : Converter.

### ISSUE THREAD

**Issue by TheIntelloBox** [walrusone/SkyWarsReloaded#50]
Hey ! :D 

Could you add a converter from Skywars to Skywars Reloaded please ? :D 

Thanks ! :D

**Comment by walrusone** [comment]
Converter for what exactly? Player data, kits, chest files?

I honestly didn't have plans to do that, but it'll depend on demand for it.

**Comment by walrusone** [comment]
And from what version of skywars? The original or some other build?

**Comment by TheIntelloBox** [comment]
V2.2.1 of this https://dev.bukkit.org/projects/skywars

I just would like to transfer chest files and the maps.

**Comment by walrusone** [comment]
It's a completely different system. Maps could be transferred by creating schematics from those and pasting them into new swr maps. The chest file would require writing a converter, which I don't have any plans to do at the moment.
