### ISSUE TITLE
Problem with map. / Paper Spigot 1.12, Java 8.

### ISSUE THREAD

**Issue by TheIntelloBox** [walrusone/SkyWarsReloaded#52]
Hey,

I created the world AngryBirds, then I have put my map. Then I tried to do /sw register AngryBirds but it doesn't work. No error, but 
[18:13:37] [Server thread/WARN]: [Multiverse-Core] Hmm Multiverse does not know about this world but it's loaded in memory.
[18:13:37] [Server thread/WARN]: [Multiverse-Core] To let Multiverse know about it, use:
[18:13:37] [Server thread/WARN]: [Multiverse-Core] /mv import angrybirds NORMAL

When I try /mv import angrybirds, it doesn't work.

**Comment by walrusone** [comment]
Did you create it using MV or with the /sw create command? I'm assuming you used /sw create. Did you use /sw save  to save the map?

**Comment by TheIntelloBox** [comment]
./sw create and yes /sw save

**Comment by walrusone** [comment]
can you post your full log of when this happened? Send me pastebin.

**Comment by TheIntelloBox** [comment]
https://hastebin.com/gisoceqije.vbs

**Comment by walrusone** [comment]
That is a issue with the reload command. I'll have to look into that. Do a clean restart instead of reloading for now.  It shouldn't of had anything to do with your map issue.

**Comment by TheIntelloBox** [comment]
I did the same, but it says that it must have 2 spawn points whereas I have put 8 beacons.

**Comment by walrusone** [comment]
Did you resave after adding the beacons?

**Comment by TheIntelloBox** [comment]
Yes. ^^

**Comment by TheIntelloBox** [comment]
So ?

**Comment by walrusone** [comment]
Is the map centered around 0,70,0? As the plugin scans for the beacons when it registers the map, the map must be centered around these coordinates and fall within the max map size noted in the config. For instance if max map size is 400, then the map must fall between -200, 0, - 200 and 200, 0, 200.

**Comment by walrusone** [comment]
Also, did you manually build the map, or did you paste I a schematic that had beacons in it. Because block entity id's have changed between minecraft versions, when pasting old maps, you sometimes have to break and replace the beacons.

**Comment by TheIntelloBox** [comment]
I have copy and paste the map then I added the beacons.

**Comment by walrusone** [comment]
What about being centered around 0, 70, 0. The y coordinate does not matter.

**Comment by TheIntelloBox** [comment]
Yes it is. ;)
Come on my server I will show you : speedcraft.omgcraft.fr:12646

**Comment by walrusone** [comment]
i'm on now if you can come online

**Comment by walrusone** [comment]
https://www.dropbox.com/s/esol7uithjdyibk/SkyWarsReloaded.jar?dl=0

**Comment by walrusone** [comment]
I meant to try to get back on your server, but I never got a chance. I'm going to close this issue, but feel free to message me on here or on spigot if you have any other issues.

**Comment by TheIntelloBox** [comment]
Come it's buggy.
