### ISSUE TITLE
Translation of "Second", "Minut", "Hour", etc.

### ISSUE THREAD

**Issue by TheIntelloBox** [walrusone/SkyWarsReloaded#56]
Hi,

Could we translate : "Second", "Minut" and"Hour".
Could we translate too : "WIN: + %p XP".

**Comment by walrusone** [comment]
I'll try to remember to do this I  the next update, I'll add it to the messages.yml. If somehow I forget, send me another message.

**Comment by walrusone** [comment]
Added to latest update.
