### ISSUE TITLE
Jenkins download links

### ISSUE THREAD

**Issue by sgdc3** [walrusone/SkyWarsReloaded#61]
Hello! Remember to add the jenkins download links in the github/spigot page ;)
https://ci.codemc.org/job/Walrusone/job/SkyWarsReloaded/

Alsojoin our discord to be notified by announces and get any support:
https://discord.gg/AGcFMu6

**Comment by sgdc3** [comment]
@walrusone

**Comment by walrusone** [comment]
Done
