### ISSUE TITLE
Spawn/chest location duplication

### ISSUE THREAD

**Issue by x1p** [walrusone/SkyWarsReloaded#63]
I ran into a bug that all spawn point, chest and sign locations etc are multiplied by, sometimes 2, but mostly 4!
This means that a map that says 32 players can join instead of 8.

This may have happened after swm refresh (refresh map data) after I edited the events.

**Comment by lukasvdgaag** [comment]
This should not be happening, but there isn't much we can do about it. Can you look into your mapData file and look how many spawns there are?

**Comment by x1p** [comment]
As said. Spawn point did also multiply.
Our game is closed. So I don't think this will happen anymore. But if this plugin wants to continue development, this maybe taken into consideration.

**Comment by walrusone** [comment]
I'll look into this and see if I can duplicate it. Thanks
