### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by x1p** [walrusone/SkyWarsReloaded#64]
I think I discovered a few possible typos on the main spigotmc page:

/sw register [mapname] should be /swm register [mapname]
/sw refreshmaps should be /swm refresh

Under the arenas manager: "Freindly" shouldn't be "Friendly"?​

**Comment by lukasvdgaag** [comment]
There are a lot of typos on the SWR spigot page, but as the owner is no longer offline, we won't be able to fix these. Thanks though

**Comment by walrusone** [comment]
Fixed. I'll look for more typos later.
