### ISSUE TITLE
Option menu disabling

### ISSUE THREAD

**Issue by x1p** [walrusone/SkyWarsReloaded#65]
When options menu is set to false the ender eye does not disappear

config:
enabledMenus:
...
  options: false
  optionsSlot: 8

**Comment by lukasvdgaag** [comment]
The menu is disabled, but is just still in your inventory.
If you clear your inventory and join again, the options item will be gone.

**Comment by x1p** [comment]
Did not work for me, but I solved this one by installing a plugin which clears your inventory every time a player joins. This solves it, but this is not how it should be.

**Comment by walrusone** [comment]
Hmm, I'll look at this.  I don't clear inventory on join, because some users wish to keep inventories. I may be able to add a toggle to clear inventory on join.
