### ISSUE TITLE
Unability to clone this repository without running through Maven errors

### ISSUE THREAD

**Issue by Revxrsal** [walrusone/SkyWarsReloaded#69]
Hello. I must admit I've really liked this plugin and was looking to adding my own touches to it, so I thought cloning is the way. Except that, I can't clone without running into Maven errors. I can tell that you have the NMS libraries on your local machine, so I would really appreciate if you can enlighten me and explain how would I go with modifying the code freely. Thanks.

Regards

**Comment by walrusone** [comment]
Hmmm, what IDE are you using? I use to host the NMS locally on my machine, but I haven't done that for a while. All should be available through the spigot repository in the pom dependencies.
