### ISSUE TITLE
Lowering TPS server start lagging ends crashing

### ISSUE THREAD

**Issue by IlPicasso** [walrusone/SkyWarsReloaded#7]
The server maintains with 200 players at 19 TPS

Suddenly TPS lowers to 9TPS or 4TPS

These are the timings

http://timings.aikar.co/?url=11772288

Probably is caused by many maps restarting at once (probably)

We are using Java 8 

Inspecting logs I found this 
http://hastebin.com/uvusagubal.avrasm

**Comment by Kyle1264x** [comment]
HelpfulMobs v2.8.4 Total: 843.18 s  Pct: 3.53% seems to be an issue as well.

Are you on the most recent version?

**Comment by IlPicasso** [comment]
I will try removing it however I don't think it is the issue

Maps wont restart and crash

**Comment by danielbeltejar** [comment]
Screenshot
![IIssue](http://imagenes.comugamers.com/images/2015/06/27/2015-06-27193449.png)

**Comment by walrusone** [comment]
Are you having any errors in your console, either when players die, or when the game ends. This is most often caused by scoreboard issues, but it's possible it could be another error.

**Comment by danielbeltejar** [comment]
http://hastebin.com/uvusagubal.avrasm that.

**Comment by walrusone** [comment]
Is that the only error you are getting?

**Comment by danielbeltejar** [comment]
Yes

**Comment by walrusone** [comment]
Ok, I'll have to add a null pointer check at that line. I'll do it as soon as I can.

**Comment by danielbeltejar** [comment]
Thanks

**Comment by IlPicasso** [comment]
Awesome man, thanks a lot

We will be sending you a donation after this :)

We really appreciate this
