### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by jfcatano** [walrusone/SkyWarsReloaded#70]
Hello! Does the plugin have rotation mode? That is, the games are rotating on the posters. When the game starts, one that is available is placed on the poster.

**Comment by walrusone** [comment]
No. It has many different join options, but not a poster rotation.

**Comment by jfcatano** [comment]
and this could be added?

**Comment by walrusone** [comment]
Possibly, but it'd be pretty low on the priority list.

**Comment by jfcatano** [comment]
Ok, thanks.
